apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <NAMESPACE>-ingress
  namespace: <NAMESPACE>
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
spec:
  ingressClassName: nginx
  rules:
  - host: <DOMAIN>
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ui
            port:
              number: 80
      - path: /api/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: api
            port:
              number: 80
  tls:
  - hosts:
    - "<DOMAIN>"
    secretName: tls
