apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-app-scaledobject
  namespace: <NAMESPACE>
spec:
  scaleTargetRef:
    name: app
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 1
  cooldownPeriod: 3600
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        metricName: http_requests_total
        threshold: '1'
        query: sum(increase(nginx_ingress_controller_requests{exported_namespace=~"<NAMESPACE>"}[1m]))
