name: Pull Request CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-ui:
    name: Build UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          image: ui
          sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}

  build-api:
    name: Build API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build
        with:
          image: api

  test-api:
    name: Test API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-api

  format-api:
    name: Format API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-api

  format-check-ui:
    name: Format Check UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-ui

  type-check-ui:
    name: Type Check UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/type-check-ui

  lint-ui:
    name: Lint UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint-ui
