apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: <NAMESPACE>
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: registry.digitalocean.com/codecannon/codecannon-app-base:latest
        workingDir: /var/www/html/api
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        lifecycle:
          postStart:
            exec:
              command: ['sh', '-c', 'cp -R /app/* /var/www/html && /var/www/html/download.sh && chown -R 82:82 /var/www/html && if [ ! -d "/var/www/html/storage/framework" ]; then cp -a /storage-initial/. /var/www/html/storage; fi && chown -R 82:82 /var/www/html/api/storage && php artisan key:generate ; php artisan optimize && php artisan migrate --force --seed']
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
