name: Docker Build
description: Builds a Docker image

inputs:
  image:
    description: Image identifier
    required: false
  sentry_auth_token:
    description: Sentry Auth Token
    required: true

runs:
  using: composite
  steps:
    - name: Docker build
      shell: bash
      run: |
        export GITHUB_SHA="$GITHUB_SHA"
        if [ -z "${{ inputs.image }}" ]; then
          image=""
        else
          image="-${{ inputs.image }}"
        fi
        make "build$image"
