name: Pull Request CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-ui:
    name: Build UI
    uses: docker/build-push-action@v6
    with:
      context: "ui"
      tags: ui:latest

  build-api:
    name: Build API
    uses: docker/build-push-action@v6
    with:
      context: "api"
      tags: api:latest

  test-api:
    name: Test API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-api

  format-check-api:
    name: Format Check API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-check-api

  format-check-ui:
    name: Format Check UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-check-ui

  type-check-ui:
    name: Type Check UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/type-check-ui

  lint-check-ui:
    name: Lint Check UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint-check-ui
