name: Main Push CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: build-main
  cancel-in-progress: true

jobs:
  build-ui:
    name: Build UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:ui"
          tags: ui:latest

  build-api:
    name: Build API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:api"
          tags: api:latest

  test-api:
    name: Test API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-api

  format-check-api:
    name: Format Check API
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-check-api

  format-check-ui:
    name: Format Check UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-check-ui

  type-check-ui:
    name: Type Check UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/type-check-ui

  lint-check-ui:
    name: Lint Check UI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint-check-ui
